在projects/sel4test/apps/sel4test-driver/src/main.c的sel4test_run_tests函数，跑每个test的函数。通过p *tests[i]可以查看test具体内容。

先初始化，再运行，再结束。

有些测试会创建新线程，新线程统一进入projects/sel4test/apps/sel4test-tests/src/main.c的main()函数，该函数的find_test函数会找到该测试。result = test->function((uintptr_t)&env);



# 跳过测试

在projects/sel4test/apps/sel4test-driver/src/main.c的sel4test_run_tests



# 关于test18的调试--通过

在170行，wait_for_helper(&waiter_thread);处卡住。

系统调用，和时间中断同时产生，如果先处理时间中断，我保存estat只保留ecode部分，把中断位mask掉，但是在中断返回后仍返回到系统调用的位置，会继续trap，再去检查estat，发现又同时置起，陷入死循环。

考虑先处理系统调用，再处理中断，最后是例外。 

它走了fastpath，fastpath的恢复现场函数和之期的不通用，在此处卡死，修改后可以运行。

slowpath的handleSyscall也有问题，不能设置刷新所有tlb，只刷新当前线程的tlb。





# 关于test36的调试--通过

test36的函数在projects/sel4test/apps/sel4test-tests/src/tests/fpu.c:test_fpu_multithreaded。

发现时钟中断和系统调用总是同时出现，时钟中断没有单独出现过。开qemu调试信息，查看ecfg的时钟中断没有打开。原因是初始化线程时候忘记设置ecfg。



# 关于test39的调试

测试函数在projects/sel4test/apps/sel4test-tests/src/tests/frames.c的test_unmap_on_delete（）函数。

334行卡死。



# 关于test46的调试

仅在wait_for_helper调用了fastpath，在restore时候，badge=0，msgInfo=1

la：发现在wait_for_helper之前都调用了fastpath但是fastpath检查有问题，都转进了slowpath，但是它用fastpath来接收，导致有问题？

函数调用路径：

projects/sel4test/apps/sel4test-tests/src/tests/ipc.c的wait_for_helper-->api_recv-->seL4_Recv-->loongarch_sys_recv，系统调用返回到projects/sel4test/apps/sel4test-tests/src/helpers.c的helper_thread，在entry_point进入projects/sel4test/apps/sel4test-tests/src/tests/ipc.c的wait_func，返回值是success，进入signal_helper_finished，最后进入fastpath。



c_handle_fastpath_call里面，dest的内容应该是对的

![image-20220911143058675](/home/lqt/projects/seL4projects/seL4-oscompProblemSolutions/images/8.31-sel4test调试.assets/image-20220911143058675.png)

badge=0，msgInfo=1应该也是对的。a0(r4)传递badge，a1(r5)传递msgInfo。

先使能7号断点，再使能34号，最后使能42号。



==============================================================================================================

第1次错误的地方：sender_prio: 98, waiter_prio: 100, sender_first: 1---entering wait_for_helper(&thread_a)后。

使能断点32，再使能34号fastpath断点，再使能43号断点，跳过syscall的处理。使能36号断点是wait_for_helper的正常返回。

为什么wait_for_helper里api_recv会进入sel4test_driver_wait？

第一次调用会sel4test_driver_wait名？



在basic_run_test里调用sel4test_driver_wait出错。



最终是因为switchthread_fp要切换用户线程





















